OpenBankingToolkit/openbanking-common

pom.xml
Remove plugin versions and properties not used.
=> Remove versions

pom.xml
Analytics not used in any child module
=> Remove analytics-client from dependency management

forgerock-openbanking-ui/README.md, forgerock-openbanking-ui/projects/auth/docker/Dockerfile, forgerock-openbanking-ui/projects/auth/docker/deployment-settings.js, forgerock-openbanking-ui/projects/auth/docker/start.sh, forgerock-openbanking-ui/projects/swagger/docker/Dockerfile, forgerock-openbanking-ui/projects/swagger/docker/deployment-settings.js, forgerock-openbanking-ui/projects/swagger/docker/start.sh
https://github.com/OpenBankingToolkit/openbanking-reference-implementation/issues/72
=> allow any config key to be overwritten by docker env

forgerock-openbanking-am/pom.xml, forgerock-openbanking-am/src/main/java/com/forgerock/openbanking/am/gateway/AMGateway.java, forgerock-openbanking-am/src/test/java/com/forgerock/openbanking/am/gateway/AMGatewayTest.java
The authentication principal is not correct after refactoring to
spring multi auth. To check if the user comes from X509 we need to check
for X509Authentication
=> Correct the instanceof check

forgerock-openbanking-am/pom.xml, forgerock-openbanking-jwt/pom.xml, forgerock-openbanking-model/pom.xml, forgerock-openbanking-oidc/pom.xml, pom.xml
Pulls in binaries built from the correct openbanking-uk-datamodel repo
See https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/5
=> Use new version of openbanking-parent

.github/workflows/merge-master.yml
- Previously there were made by openbankbot
=> Releases will be made by fropenbanking github user

.github/workflows/ui.yml
- Fix for https://github.com/OpenBankingToolkit/openbanking-common/issues/48
=> UI build on master now updates master-dev deploy versions

forgerock-openbanking-ui/package-lock.json, forgerock-openbanking-ui/package.json, forgerock-openbanking-ui/projects/auth/src/app/app.component.ts, forgerock-openbanking-ui/projects/auth/src/assets/i18n/en.json, forgerock-openbanking-ui/projects/auth/src/environments/environment.default.ts, forgerock-openbanking-ui/projects/auth/src/environments/environment.dev.default.ts, forgerock-openbanking-ui/projects/auth/src/scss/_all-theme.scss, forgerock-openbanking-ui/projects/swagger/src/app/app.component.ts, forgerock-openbanking-ui/projects/swagger/src/environments/environment.default.ts, forgerock-openbanking-ui/projects/swagger/src/environments/environment.dev.default.ts
https://github.com/ForgeCloud/ob-reference-implementation/issues/407
=> adding registration feature flag

forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/error/OBRIErrorType.java
Part of https://github.com/OpenBankingToolkit/openbanking-aspsp/issues/196
=> Add error type for Payment Context Code validation

.github/workflows/ui.yml, README.md, forgerock-openbanking-jwt/pom.xml, forgerock-openbanking-ui/README.md, forgerock-openbanking-ui/docker-compose-ui-integ.yml, forgerock-openbanking-ui/docker-compose.yml, forgerock-openbanking-ui/pom.xml, forgerock-openbanking-ui/ssl/dev-ob.forgerock.financial.conf, forgerock-openbanking-upgrade/pom.xml, pom.xml
Improvements to make easy build and run the UI apps on local.
Build images in simply way using maven (hack over angular app module).
```bash
mvn clean install
```
Docker compose created to run the UI services on local linked with dev-ob domain reference services.
=> Enhancement to build and run in local env the UI apps

.github/workflows/ui.yml, forgerock-openbanking-ui/pom.xml, pom.xml
- Skip the default build goal for ui non java module
- Enabled only for auth-ui and swagger-ui build goals
=> UI Build images faster skiping the default build goal

forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/SoftwareStatement.java
Part fix for https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/12
=> Store organisationId in the Software Statement

forgerock-openbanking-am/pom.xml, forgerock-openbanking-jwt/pom.xml, forgerock-openbanking-model/pom.xml, forgerock-openbanking-oidc/pom.xml, forgerock-openbanking-ssl/pom.xml, forgerock-openbanking-ui/pom.xml, forgerock-openbanking-upgrade/pom.xml, pom.xml
- stores organisationId in the Software Statement
=> Release 1.0.82

forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/SoftwareStatement.java
I've double checked the getters and setters and the `@Value` annotation will replace like with like.
=> Alternative SoftwareStatement with @JsonProperty and @Value annotations

forgerock-openbanking-am/pom.xml, forgerock-openbanking-jwt/pom.xml, forgerock-openbanking-model/pom.xml, forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/repositories/TppRepository.java, forgerock-openbanking-oidc/pom.xml, forgerock-openbanking-ssl/pom.xml, forgerock-openbanking-ui/pom.xml, forgerock-openbanking-upgrade/pom.xml, pom.xml
Add a repository object to obtain Tpps from Mongo
Part fix for https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/12
=> Add repository object to get/store Tpp objects and release version 1.0.85

forgerock-openbanking-ui/package.json
Set project version to 3.1.6-smiths-rc2
ForgeCloud/ob-deploy#620
=> Set project version to 3.1.6-smiths-rc2 (#620)

forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/error/ErrorCode.java, forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/error/OBRIErrorType.java
- Added new error codes and error types for response_types checks
- [issue 674](https://github.com/ForgeCloud/ob-deploy/issues/674)
=> 674: response_types error codes

forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/constants/OpenBankingConstants.java
- Added the scope `eventpolling` for versions 3.1.2 and 3.1.3 event notifications
Issue: https://github.com/OpenBankingToolkit/openbanking-aspsp/issues/327
=> 327: Aggregated polling scopes by version

forgerock-openbanking-am/pom.xml, forgerock-openbanking-am/src/main/java/com/forgerock/openbanking/am/gateway/AMGateway.java, forgerock-openbanking-am/src/test/java/com/forgerock/openbanking/am/gateway/AMGatewayTest.java, forgerock-openbanking-annotations/pom.xml, forgerock-openbanking-jwt/pom.xml, forgerock-openbanking-model/pom.xml, forgerock-openbanking-oidc/pom.xml, forgerock-openbanking-ssl/pom.xml, forgerock-openbanking-upgrade/pom.xml, pom.xml
Use the forgerock version of spring-security-multi-auth library
Issue: https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/34
=> 32: take ownership of spring cloud multi auth

forgerock-openbanking-am/pom.xml, forgerock-openbanking-annotations/pom.xml, forgerock-openbanking-jwt/pom.xml, forgerock-openbanking-model/pom.xml, forgerock-openbanking-oidc/pom.xml, forgerock-openbanking-ssl/pom.xml, forgerock-openbanking-upgrade/pom.xml, pom.xml
Release 1.2.1
Contains some refactoring work that contributes to issue 422
https://github.com/OpenBankingToolkit/openbanking-aspsp/issues/422
=> Release 1.2.1

forgerock-openbanking-am/pom.xml, forgerock-openbanking-annotations/pom.xml, forgerock-openbanking-jwt/pom.xml, forgerock-openbanking-model/pom.xml, forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/constants/OpenBankingConstants.java, forgerock-openbanking-oidc/pom.xml, forgerock-openbanking-ssl/pom.xml, forgerock-openbanking-upgrade/pom.xml, pom.xml
Issue: https://github.com/OpenBankingToolkit/openbanking-aspsp/pull/440
=> 440: Refactor client registration code - release 1.2.2

forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/DirectorySoftwareStatement.java, forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/DirectorySoftwareStatementOpenBanking.java, forgerock-openbanking-model/src/test/java/com/forgerock/openbanking/model/DirectorySoftwareStatementTest.java
The abstract class DirectorySoftware Statement was not serialsable or
deserialisable
Issue: https://github.com/ForgeCloud/ob-deploy/issues/775
=> 775: Fix serialisation of abstract DirectorySoftwareStatement

forgerock-openbanking-am/pom.xml, forgerock-openbanking-annotations/pom.xml, forgerock-openbanking-jwt/pom.xml, forgerock-openbanking-model/pom.xml, forgerock-openbanking-oidc/pom.xml, forgerock-openbanking-ssl/pom.xml, forgerock-openbanking-upgrade/pom.xml, pom.xml
Release 1.2.6 with #134 in which fixed serialisation/de-serialisation of DirectorySoftwareStatement
=> Release 1.2.6

forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/AuthorisationClaim.java, forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/DirectorySoftwareStatementOpenBanking.java, forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/OrganisationAuthorityClaims.java, forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/OrganisationContact.java, forgerock-openbanking-model/src/test/java/com/forgerock/openbanking/model/DirectorySoftwareStatementTest.java, forgerock-openbanking-model/src/test/resources/SSAs/ForgeRockDirectorySSA.json, forgerock-openbanking-model/src/test/resources/SSAs/OpenBankingAutomatedTestingSSA.json
https://github.com/ForgeCloud/ob-deploy/issues/793
=> 793: Add decent tests and fix serialisation issue

forgerock-openbanking-am/pom.xml, forgerock-openbanking-annotations/pom.xml, forgerock-openbanking-jwt/pom.xml, forgerock-openbanking-model/pom.xml, forgerock-openbanking-oidc/pom.xml, forgerock-openbanking-ssl/pom.xml, forgerock-openbanking-upgrade/pom.xml, pom.xml
Add decent tests and fix ForgeCloud/ob-deploy#793
=> Create release 1.2.8

.github/workflows/ui-release.yml, .github/workflows/ui.yml
- Upgrade github workflows with bot version 1.0.7
Issue: https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/39
=> 39: Branch protection bot upgrade

forgerock-openbanking-am/pom.xml, forgerock-openbanking-annotations/pom.xml, forgerock-openbanking-jwt/pom.xml, forgerock-openbanking-model/pom.xml, forgerock-openbanking-oidc/pom.xml, forgerock-openbanking-ssl/pom.xml, forgerock-openbanking-upgrade/pom.xml, pom.xml
Use latest 3.1.8r5 swagger generated data models
=> Release 1.2.13

forgerock-openbanking-annotations/src/main/java/com/forgerock/openbanking/api/annotations/OBReference.java
- Added the obReference to manage enable/disable endpoints for VRP apis
Issue: https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/45
=> 45: vrp controllers

forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/error/ErrorCode.java, forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/error/OBRIErrorType.java
Issue: https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/36
=> 36: Add new ErrorCode and ErrorTypes for VRP

forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/error/OBRIErrorType.java, forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/error/VRPErrorControlParametersFields.java, pom.xml
- added objects for vrp validations
Issue: https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/48
=> 48: vrp payment controller validations

.github/workflows/ui-release.yml, .github/workflows/ui.yml
- Fix node version on github actions using [actions/setup-node@v2](https://github.com/actions/setup-node)
=> Fix node version

forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/error/ErrorCode.java, forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/error/OBRIErrorType.java
Issue: https://github.com/ForgeCloud/ob-deploy/issues/815
=> 815: Add errors for customer info journey

forgerock-openbanking-am/pom.xml, forgerock-openbanking-annotations/pom.xml, forgerock-openbanking-jwt/pom.xml, forgerock-openbanking-model/pom.xml, forgerock-openbanking-oidc/pom.xml, forgerock-openbanking-ssl/pom.xml, forgerock-openbanking-upgrade/pom.xml, pom.xml
Issue: https://github.com/ForgeCloud/ob-deploy/issues/815
=> 815: Use uk-datastore with CustomerInfo datatypes and release v1.3.2

forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/error/ErrorCode.java, forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/error/OBRIErrorType.java
- Added error types and codes to return errors in the dialog
Issue: https://github.com/ForgeCloud/ob-deploy/issues/824
=> 824: Customer info dialog

.github/workflows/merge-master.yml, .github/workflows/pr.yml, .github/workflows/release.yml
Will cache .m2 against a hash of the pom files.
=> Add github action caching

forgerock-openbanking-am/pom.xml, forgerock-openbanking-annotations/pom.xml, forgerock-openbanking-jwt/pom.xml, forgerock-openbanking-model/pom.xml, forgerock-openbanking-oidc/pom.xml, forgerock-openbanking-ssl/pom.xml, forgerock-openbanking-upgrade/pom.xml, pom.xml
Contains datatypes for CustomerInfo consent dialogs
=> Release 1.3.3

forgerock-openbanking-am/pom.xml, forgerock-openbanking-annotations/pom.xml, forgerock-openbanking-jwt/pom.xml, forgerock-openbanking-model/pom.xml, forgerock-openbanking-oidc/pom.xml, forgerock-openbanking-ssl/pom.xml, forgerock-openbanking-upgrade/pom.xml, pom.xml
Release in preparation for Q1 deployments. 
Contains 
- CustomerInfo
- Fix for Manual Registration
=> Release 1.3.4

forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/error/ErrorCode.java, forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/error/OBRIErrorType.java
Issue: https://github.com/ForgeCloud/ob-deploy/issues/870
=> 870: Adding error codes for VRP Payment Limit breaches

forgerock-openbanking-am/pom.xml, forgerock-openbanking-annotations/pom.xml, forgerock-openbanking-jwt/pom.xml, forgerock-openbanking-model/pom.xml, forgerock-openbanking-oidc/pom.xml, forgerock-openbanking-ssl/pom.xml, forgerock-openbanking-upgrade/pom.xml, pom.xml
Release 1.5.1 with #183 which addresses https://github.com/forgecloud/ob-deploy/issues/888
=> Release 1.5.1

forgerock-openbanking-am/pom.xml, forgerock-openbanking-annotations/pom.xml, forgerock-openbanking-jwt/pom.xml, forgerock-openbanking-model/pom.xml, forgerock-openbanking-oidc/pom.xml, forgerock-openbanking-ssl/pom.xml, forgerock-openbanking-upgrade/pom.xml, pom.xml
Release 1.5.2 containing a fix for https://github.com/forgecloud/ob-deploy/issues/949
=> Release 1.5.2

forgerock-openbanking-ui/README.md, forgerock-openbanking-ui/package-lock.json, forgerock-openbanking-ui/package.json
- openbanking-ngx-common dependency updated
=> ui commons version upgrade
