- forgerock-openbanking-ui/package-lock.json
- forgerock-openbanking-ui/package.json
Fix the Error:
> node-sass@4.12.0 install /Users/jorge.sanchez-perez/Documents/forgerock/git/openbankingtoolkit/openbanking-directory/forgerock-openbanking-ui/node_modules/node-sass
node scripts/install.js
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/darwin-x64-79_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/darwin-x64-79_binding.node":
HTTP error 404 Not Found
Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.
export HTTP_PROXY=http://example.com:1234
or configure npm proxy via
npm config set proxy http://example.com:8080
node[32074]: ../src/signal_wrap.cc:159:void node::DecreaseSignalHandlerCount(int): Assertion `(new_handler_count) >= (0)' failed.
1: …
> fix node sass version to the latest

- forgerock-openbanking-am/pom.xml
- forgerock-openbanking-jwt/pom.xml
- forgerock-openbanking-model/pom.xml
- forgerock-openbanking-oidc/pom.xml
- forgerock-openbanking-ssl/pom.xml
- forgerock-openbanking-upgrade/pom.xml
- pom.xml
- This picks up the eidas-psd2-cert library (code in OpenBankingToolkit)
rather than the forgerock-eidas-psd2-sdk that was in ForgeCloud
- This has a part fix for
https://github.com/OpenBankingToolkit/openbanking-reference-implementation/issues/81
> Use latest openbanking-parent pom

- .github/workflows/pr.yml
- .github/workflows/ui.yml
Push/pull Docker images to/from GCR instead of Codefresh. This references a new Github secret called `GCR_JSON_KEY` which is a new access token for Google Cloud with a limited scope for the container registry.
Part of https://github.com/ForgeCloud/ob-deploy/issues/468
> Push Docker images to GCR instead of Codefresh

- forgerock-openbanking-am/pom.xml
- forgerock-openbanking-jwt/pom.xml
- forgerock-openbanking-model/pom.xml
- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/SoftwareStatement.java
- forgerock-openbanking-oidc/pom.xml
- forgerock-openbanking-ssl/pom.xml
- forgerock-openbanking-ui/pom.xml
- forgerock-openbanking-upgrade/pom.xml
- pom.xml
It would help TPPs doing message signing if org_id and software_id
fields existing in both ForgeRock and OpenBanking issued Software
Statements. This will facilitate the creation of JWS signatures for
message signing.
Part fix for https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/12
> Allign OpenBanking and Forgerock software statement fields - and release 1.0.83

- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/constants/OIDCConstants.java
- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/error/UnsupportedOIDCAuthMethodsException.java
- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/error/UnsupportedOIDCGrantTypeException.java
- forgerock-openbanking-model/src/test/java/com/forgerock/openbanking/constants/OIDCConstantsTest.java
- Created new Exceptions to manage the unsupported OIDC constants types
Issue: https://github.com/ForgeCloud/ob-deploy/issues/742
> 742: token endpoint 500 error

- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/Tpp.java
Tpp used to return it's OIDCRegistrationResponse and allow clients to
then query that object for information. This breaks the law of dimiter.
Instead the Tpp can return data held within it's agregated classes to
reduce coupling. In this case Tpp can now be asked for the Tpp's
registration access token. This means the caller of the Tpp class
doesn't need to know anything about the OIDCRegistration response.
This helps write tests that were required during work to improve
logging and error handling for the DELETE /register/{{ClientId}}
endpoints.
Issue: https://github.com/OpenBankingToolkit/openbanking-aspsp/issues/422
> 422: Refactoring Tpp - applying law of dimeter

- forgerock-openbanking-upgrade/src/main/java/com/forgerock/openbanking/upgrade/EntitiesVersionRepository.java
- forgerock-openbanking-upgrade/src/main/java/com/forgerock/openbanking/upgrade/UpgradeApplication.java
- forgerock-openbanking-upgrade/src/main/java/com/forgerock/openbanking/upgrade/UpgradeDatabase.java
- Added clean duplication versions method when collect the entitiesVersion to get unique versions
- Added new repository method to get the current upgrade system version if exist
Issue: https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/38
> 38: Duplication version error fix

- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/AuthorisationClaim.java
- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/DirectorySoftwareStatement.java
- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/DirectorySoftwareStatementOpenBanking.java
- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/OrganisationAuthorityClaims.java
- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/OrganisationContact.java
- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/Tpp.java
- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/repositories/TppRepository.java
Refactor the Tpp Class to hold sufficient information to allow searching for Tpp record based on authorizationNumber, add orgId and softwareId.
Store the full DirectorySoftwareStatement in the Tpp record rathern than just the serialized json software statement.
-----
Add new repository method `findByAuthorisationNumber` and the Tpp class has both the softwareId and AuthorisationNumber that stores the certificate subject 2.5.4.97.
The Tpp class will now store the SSA as both string and object making it backwards compatible with old registrations. New registrations will use the DirectorySoftwareStatement.
issue: https://github.com/ForgeCloud/ob-deploy/issues/775
> 775: Allow Tpps to register more than one Software Statement 

- forgerock-openbanking-am/pom.xml
- forgerock-openbanking-annotations/pom.xml
- forgerock-openbanking-jwt/pom.xml
- forgerock-openbanking-model/pom.xml
- forgerock-openbanking-oidc/pom.xml
- forgerock-openbanking-ssl/pom.xml
- forgerock-openbanking-upgrade/pom.xml
- pom.xml
Includes #132 
Refactor the Tpp Class to hold sufficient information to allow searching for Tpp record based on authorizationNumber, add orgId and softwareId.
Store the full DirectorySoftwareStatement in the Tpp record rathern than just the serialized json software statement.
Add new repository method findByAuthorisationNumber and the Tpp class has both the softwareId and AuthorisationNumber that stores the certificate subject 2.5.4.97.
The Tpp class will now store the SSA as both string and object making it backwards compatible with old registrations. New registrations will use the DirectorySoftwareStatement.
issue: ForgeCloud/ob-deploy#775
> Release 1.2.5

- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/DirectorySoftwareStatement.java
- forgerock-openbanking-model/src/test/java/com/forgerock/openbanking/model/DirectorySoftwareStatementTest.java
Serialisation is based on the value of the `iss` field of the software
statement, and the code expected OpenBanking iss to be "OpenBanking",
however in OB Directory Issued Software Statements the iss field is
actually "OpenBanking Ltd"
Issue: https://github.com/ForgeCloud/ob-deploy/issues/793
> 793: Can serialise OpenBanking software statements

- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/DirectorySoftwareStatement.java
- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/DirectorySoftwareStatementOpenBanking.java
- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/SoftwareStatement.java
- forgerock-openbanking-model/src/test/java/com/forgerock/openbanking/model/DirectorySoftwareStatementTest.java
I found that when data was deserialised from mongo the iss field was
invisible. This was recreated in the DirectorySoftwareStatementTest and
fixed by the addition of a visible = true flag in the @JsonTypeInfo
annotation arguments.
Also in this PR is the addition of the iss field to the
SoftwareStatement that represents the software statements created by the
ForgeRock directory. This is necessary as the Postman tests use the
directory server API to obtain a current software statement and that
didn't have an iss field set, although the obtained by the directory UI
did have an iss statement. The lack of the iss field meant that the
SoftwareStatement couldn't be serialised/deserialised and caused
problems for the Postman tests.
Issue: https://github.com/ForgeCloud/ob-deploy/issues/793
> 793: Fix more issues with DirectorySoftwareStatement serialisation

- forgerock-openbanking-am/pom.xml
- forgerock-openbanking-annotations/pom.xml
- forgerock-openbanking-jwt/pom.xml
- forgerock-openbanking-model/pom.xml
- forgerock-openbanking-oidc/pom.xml
- forgerock-openbanking-ssl/pom.xml
- forgerock-openbanking-upgrade/pom.xml
- pom.xml
793: Fix more issues with DirectorySoftwareStatement serialisation
I found that when data was deserialised from mongo the iss field was
invisible. This was recreated in the DirectorySoftwareStatementTest and
fixed by the addition of a visible = true flag in the @JsonTypeInfo
annotation arguments.
Also in this PR is the addition of the iss field to the
SoftwareStatement that represents the software statements created by the
ForgeRock directory. This is necessary as the Postman tests use the
directory server API to obtain a current software statement and that
didn't have an iss field set, although the obtained by the directory UI
did have an iss statement. The lack of the iss field meant that the
SoftwareStatement couldn't be serialised/deserialised and caused
problems for the Postman …
> Create release 1.2.9

- forgerock-openbanking-am/pom.xml
- forgerock-openbanking-annotations/pom.xml
- forgerock-openbanking-jwt/pom.xml
- forgerock-openbanking-model/pom.xml
- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/constants/CountryCodes.java
- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/constants/OpenBankingConstants.java
- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/DirectorySoftwareStatement.java
- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/DirectorySoftwareStatementOpenBanking.java
- forgerock-openbanking-model/src/test/java/com/forgerock/openbanking/model/DirectorySoftwareStatementTest.java
- forgerock-openbanking-oidc/pom.xml
- forgerock-openbanking-ssl/pom.xml
- forgerock-openbanking-upgrade/pom.xml
- pom.xml
Release version 1.2.10 which contains;
796: Add MATLS checks to DCR code
Common code needed to perform MATLS checks to ensure the MATLS transport
cert presented for registration and the software statement being used
for registration were issed to the same ApiClient (TPP)
Issue: https://github.com/ForgeCloud/ob-deploy/issues/796
> Release 1.2.10 with 796: add matls checks to dcr code

- pom.xml
Issue: https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/45
> 45: Use latest parent with 3.1.8r5 datamodels

- forgerock-openbanking-am/pom.xml
- forgerock-openbanking-annotations/pom.xml
- forgerock-openbanking-jwt/pom.xml
- forgerock-openbanking-model/pom.xml
- forgerock-openbanking-oidc/pom.xml
- forgerock-openbanking-ssl/pom.xml
- forgerock-openbanking-upgrade/pom.xml
- pom.xml
45: Use fixed uk-datamodel for 3.1.8
OBFundsConfirmationConsentResponse1Data uses OBExternalRequestStatus1Code rather than the StatusEnum
defined within the class.
Issue: https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/45
> 45: Release 1.2.14 & use latest uk datamodel

- forgerock-openbanking-annotations/src/main/java/com/forgerock/openbanking/api/annotations/OBGroupName.java
- forgerock-openbanking-annotations/src/main/java/com/forgerock/openbanking/api/annotations/OBReference.java
- pom.xml
Note: We now pull in a snapshot of openbanking-parent while we develop
this feature. We will need to change this to release version when
stable.
Issue: https://github.com/OpenBankingToolkit/openbanking-parent/pull/284
> 815: Add enums to allow CustomerInfo endpoint in discovery

- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/serialiser/IsoLocalDateDeserializer.java
- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/serialiser/IsoLocalDateSerializer.java
- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/serialiser/config/SerialiserConfig.java
- forgerock-openbanking-model/src/test/java/com/forgerock/openbanking/serialiser/IsoLocalDateDeserializerTest.java
- forgerock-openbanking-model/src/test/java/com/forgerock/openbanking/serialiser/IsoLocalDateSerializerTest.java
Fixing an issue where LocalDate objects are being JSON serialized by the default serializer which produces output as an int[].
Adding new Jackson serializer classes: IsoLocalDateSerializer & IsoLocalDateDeserializer to produce an ISO date string of the format "yyyy-MM-dd" for LocalDate objects. These classes are then configured to be used when serializing any LocalDate object using Jackson.
Issue: https://github.com/ForgeCloud/ob-deploy/issues/871
> 871: Adding custom Jackson serializer & deserializer for LocalDate objects

- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/error/ErrorCode.java
- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/model/error/OBRIErrorType.java
- pom.xml
- Adding error messages and codes for extended VRP validation rules
- Updating parent versions to 2.1.0 in order to supports OB version 3.1.10
Issue: https://github.com/ForgeCloud/ob-deploy/issues/883
> 883: Adding Error messages for VRP extended validation rules

- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/constants/CountryCodes.java
Danish and Latvian TPPs were failing to do dynamic client registration
due to a country code lookup that failed.
Issue: https://github.com/forgecloud/ob-deploy/issues/888
> 888: Allow Danish and Latvian eIDAS cert TPP registration

- forgerock-openbanking-model/src/main/java/com/forgerock/openbanking/constants/CountryCodes.java
OBIE use LTH not LTU
Issue: https://github.com/forgecloud/ob-deploy/issues/949
> 949: Fix Three letter code mapping for Latvia
